### ISSUE TITLE
After 1 hour i start running validator node, i getting this

### ISSUE THREAD

**Issue by GrPanda** [sora-xor/sora2-network#3]
Version: 0.1.0-2278bc0-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/p                                                                                                                                                             anicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/p                                                                                                                                                             anicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/s                                                                                                                                                             ys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/p                                                                                                                                                             anicking.rs:493:5
   5: std::panicking::begin_panic_fmt
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/p                                                                                                                                                             anicking.rs:435:5
   6: tokio::time::wheel::Wheel<T>::set_elapsed
   7: tokio::time::wheel::Wheel<T>::poll
   8: tokio::time::driver::Driver<T>::process
   9: <tokio::time::driver::Driver<T> as tokio::park::Park>::park
  10: <tokio::park::either::Either<A,B> as tokio::park::Park>::park
  11: <tokio::runtime::park::Parker as tokio::park::Park>::park
  12: tokio::runtime::thread_pool::worker::Context::park_timeout
  13: tokio::runtime::task::raw::poll
  14: tokio::runtime::handle::Handle::enter
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/alloc/src                                                                                                                                                             /boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/alloc/src                                                                                                                                                             /boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/s                                                                                                                                                             ys/unix/thread.rs:71:17
  18: start_thread
  19: clone

Thread 'tokio-runtime-worker' panicked at 'elapsed=367374; when=367373', /opt/ru                                                                                                                                                             st/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/time/wheel/mod.rs:2                                                                                                                                                             23

This is a bug. Please report it at:

**Comment by GrPanda** [comment]
Hi,
i am runing on Virtual Machine with minimal Ubuntu.
starting with
docker run --rm --name validator-client -p 127.0.0.1:9933:9933 -p 127.0.0.1:9944:9944 -v pwd:/chain sora2/substrate:1.0.0 --chain main --base-path /chain --validator --unsafe-rpc-external --unsafe-ws-external --rpc-methods=Unsafe --name=Name --execution Wasm --telemetry-url "wss://telemetry.polkadot.io/submit/ 0"

It's running well on windows withiout VM, but i got endlessly growing C:\Users\user\AppData\Local\Docker\wsl\data\ext4.vhdx file, so i trying Ubuntu on VM.

It can be VM problem or not, but happening periodically, so i thinking that this information will be helpfull for you.
