### ISSUE TITLE
Panic issue

### ISSUE THREAD

**Issue by BDRSora** [sora-xor/sora2-network#6]
Thread 'tokio-runtime-worker' panicked at 'assertion failed: res.eax == 0', /opt/rust/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-8.1.2/src/lib.rs:295

This occurred when trying to synchronize a validator node. Anyone know how to resolve this issue?

**Comment by memret** [comment]
I am getting same error with this cpu. Did you solve your issue?

Intel Xeon-E 2386G - 6c/12t - 3.5 GHz/4.7 GHz

**Comment by Nolan730** [comment]
I'am having this error while trying to run node on my server. After searching a bit i find out wasmtime updated their version to solve it. Is it possible for team to compile node files(inside docker images) with new version of wasmtime?

Thread 'tokio-runtime-worker' panicked at 'assertion failed: res.eax == 0', /opt/rust/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-8.1.2/src/lib.rs:295
My cpu: Intel Xeon-E 2386G - 6c/12t - 3.5 GHz/4.7 GHz

wasmtime update: https://github.com/bytecodealliance/wasmtime/pull/2607
substrate update: https://github.com/paritytech/substrate/issues/8024

**Comment by Nolan730** [comment]
This isnt solved with 1.4.0. It still crashes with same error.

Thread 'main' panicked at 'assertion failed: res.eax == 0', /opt/rust/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-8.1.2/src/lib.rs:295
